# Generated by Django 2.1.5 on 2021-09-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210922_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='information',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
